name: build image
on: [push]
jobs:
  create-ktor-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          path: ./jvm-fw-monitoring-examples-k8s
      - name: Checkout target repox
        uses: actions/checkout@master
        with:
          repository: Openvalue-muc/jvm-fw-monitoring-examples
          path: ./jvm-fw-monitoring-examples
          github-token: ${{ github.token }}
          token: ${{ secrets.TOKEN }}
      - name: Configure JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build :ktor-monitoring:build
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: jvm-fw-monitoring-examples-k8s/Dockerfile
          tags: jjbeto/jvm-fw-monitoring-examples-ktor
          build-args: |
            JAR_FILE=ktor-monitoring/build/libs/ktor-monitoring-1.0-SNAPSHOT-all.jar
      - name: Push image
        run: docker push jjbeto/jvm-fw-monitoring-examples-ktor:latest
